name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image (without push)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false

  build-and-push:
    needs: build  
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/uplotnikova20-hue/student-converter:latest
            ghcr.io/uplotnikova20-hue/student-converter:${{ github.sha }}
